# dans docker-compose.prod.yml

services:
  django:
    # On spécifie l'image à télécharger depuis GitHub Container Registry
    image: ghcr.io/delanoche92/projet_cms:latest
    container_name: monprojet_prod_django
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production   
    volumes:
      - ./.envs:/app/.envs:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: monprojet_prod_postgres
    restart: always
    volumes:
      - monprojet_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

volumes:
  monprojet_prod_postgres_data:
